version: '3'

services:
  gitea:
    image: docker.io/gitea/gitea:latest
    restart: always
    volumes:
      - "git_data:/data"
    ports:
      - "3000:3000"
      - "2222:22"
    environment:
      DB_USER: gitea
      DB_NAME: gitea
      DB_PASSWD: gitea 
      DB_TYPE: postgres
      DB_HOST: db:5432
  db:
    image: docker.io/postgres:13.16-alpine
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: gitea 
      POSTGRES_USER: gitea
      POSTGRES_DB: gitea
volumes:
  git_data: {}
  db_data: {}
